[package]
name = "connector"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Jens Reidel <jens@troet.org>"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
jni = "0.17"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
